app/controllers/concerns/word_filter.rb
app/javascript/controllers/filter_controller.js
app/views/filters/_form.html.haml
config/locales/filter.de.yml
spec/features/filter_spec.rb

Closes #5.
This adds an "all" option to the search.
Note that this goes into the `friendly_id` branch, only to avoid database troubles for convenience.

Search across all word types

---

app/views/nouns/show.html.haml

Closes #6.
Adds the singular article in front of the noun in the title:
If no genus is selected for the noun, no article is displayed.

Add article to noun title

---

app/views/words/_versions.html.haml
db/migrate/20221111105512_convert_papertrail_yaml_to_json.rb
db/schema.rb
spec/models/word_spec.rb

There is an incompatibility between Rails 7 and newer versions of paper_trail. By default paper_trail uses YAML to serialize objects and changes. ActiveRecord nowadays only allows safe YAML to be loaded, which is not the case for objects and changes.
This causes the following error when loading changesets:
```ruby
changes = Word.first.versions.last.object_changes
PaperTrail.serializer.load(ch)
~/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Time (Psych::DisallowedClass)
```
Which causes the displayed change history to be empty as empty changes are reported. The changes are still recorded correctly in the database though.
We therefore convert the YAML based column to use JSON instead.
* Changing an example sentence does not create …

Fix word history

---

app/controllers/function_words_controller.rb
app/javascript/controllers/filter_controller.js
app/models/ability.rb
app/views/filters/_form.html.haml
app/views/function_words/_function_word.html.haml
app/views/function_words/index.html.haml
app/views/function_words/show.html.haml

Fixes #26.
* Allows everyone (also guests) to see function words (including their index and detail page). Creating function words or editing still requires privileges.
* Adds function word to be searchable by type
* Fix layout and click on function words in search results. We always display a grey box on the left as function words cannot have images. However, when displayed among other words, it looks strange without the grey box.

Search | Allow function words to be found correctly

---

app/models/word.rb
app/views/words/_general_form.html.haml
config/locales/models.de.yml
spec/features/friendly_id_spec.rb
spec/models/friendly_id_spec.rb

Closes #32.
* Add field to edit the slug (only when editing, not when creating).
* Make sure slugs are lowercased when updated
* We hide the input field for the slug when creating new words. For tech savy people it is still possible to set the initial slug by editing the HTTP request. As the slug is editable afterwards I can't think of a way this could be exploited. I therefore decided to abstain from introducing verbose backend logic to disallow the slug on creation.
* I called the slug field "URL Term". Let me know if you know a better wording or if we should just call it "Slug" in German as well.
* I decided not to show the slug on the detail page of the word for simplicity. Let me know if it makes sense to add it there as well!

Allow slugs to be edited

---

app/models/ability.rb

Fixes #52.
Removes the navigation item for anonymous users. That also means that they don't have access to any word cards. They shouldn't though, as they only see the default view.

Fix navigation of word cards for anonymous users

---

app/views/schools/index.html.haml

This fixes the display of the new school button, depending on if the current user is able to create a new school or not.

Hide 'new school' button for teachers

---

app/controllers/learning_pleas_controller.rb
app/models/ability.rb
app/models/learning_group.rb
app/models/learning_plea.rb
app/models/list.rb
app/views/learning_groups/show.html.haml
app/views/learning_pleas/new.html.haml
config/locales/notices.de.yml
config/locales/views.de.yml
config/routes.rb
db/migrate/20221116170556_create_learning_pleas.rb
db/schema.rb
spec/features/learning_groups_spec.rb

Related to #16.
This allows to add word lists to learning groups.

Wörterklinik | Add word lists to learning groups

---

app/controllers/learning_pleas_controller.rb
app/controllers/lists_controller.rb
app/models/ability.rb
app/models/student.rb
app/services/flashcards.rb
app/views/learning_groups/show.html.haml
app/views/lists/show.html.haml
spec/features/flashcards_spec.rb
spec/models/flashcards_spec.rb

Related to #16.
* Adding or removing a word from a list, adds or removes that word from the Wörterklinik of all students who have a connection to that list via a learning group
* Adding or removing a list from a learning group, will add or remove words from the Wörterklinik of the students of that learning group
* Ensures that words only appear once in the "Wörterklinik" of a student, even if the word appears in multiple word lists connected to the learning group

Wörterklinik | Change words for students when lists change

---

app/assets/stylesheets/application.tailwind.css
app/views/themes/_form.html.haml
app/views/themes/edit.html.haml
app/views/themes/new.html.haml
config/locales/actions.de.yml
spec/features/themes_spec.rb

Closes #51.
* Change theme creation into a 2 step process:
* Increase minimum size of template editor

Themes | Change creation of themes to a 2-step process

---

Gemfile.lock
app/controllers/adjectives_controller.rb
app/controllers/concerns/list_addable.rb
app/controllers/nouns_controller.rb
app/controllers/searches_controller.rb
app/controllers/verbs_controller.rb
app/views/filters/_add_to_list.html.haml
app/views/filters/add_to_list.html.haml
app/views/shared/_filter.html.haml
app/views/words/_index.html.haml
config/locales/filter.de.yml
config/routes.rb
spec/features/filter_spec.rb

When filtering words, the result can now be added to a word list. Related to #16.

Word lists | Add filtered words

---

app/views/lists/show.html.haml

The edit button of word lists was always shown. We should only show it if the user has permission to edit the list.

Fix showing of edit button depending on permissions

---

Gemfile
Gemfile.lock
config/initializers/route_downcaser.rb
spec/features/nouns_spec.rb

Closes #27.
- Redirect `/HAUs` to `/haus` using a 301
- URLs with an additional slash in them, such as `/page/impressum`, are not redirected. This is mainly to avoid hard to track bugs in library code, such as Devise or ActiveStorage (e.g. when using case sensitive tokens in URLs). We still redirect index actions of controllers such as `/NOUNS` though.

Add redirect for words to downcased URLs

---

Gemfile
Gemfile.lock
app/controllers/concerns/word_filter.rb
app/models/word.rb
app/views/filters/_form.html.haml
app/views/shared/_filter.html.haml
config/locales/filter.de.yml
db/migrate/20221202144813_add_cologne_phonetics_to_words.rb
db/schema.rb
spec/features/filter_spec.rb
spec/models/history_spec.rb
spec/models/word_spec.rb

Closes #20.
This implements searching by cologne phonetics.
* Adds `Words#cologne_phonetics` which updates whenever a word changes
* Add a filter function to search by cologne phonetics
* Add an input field to the power search
* Change the filter input fields of nouns, verbs and adjectives to use phonetic search
This does not yet implement the more complex searching behavior which changes for every added letter as proposed in #20.

Add cologne phonetics

---

config/initializers/route_downcaser.rb
spec/requests/nouns_controller_spec.rb

Closes #101.
Image URLs of activestorage must not be downcased as the signed ID would then be invalid.

Fix image URLs

---

Gemfile
Gemfile.lock
app/controllers/schools_controller.rb
app/models/school.rb
app/views/schools/_form.html.haml
app/views/schools/_school.html.haml
app/views/schools/show.html.haml
config/initializers/phony.rb
config/locales/models.de.yml
config/locales/views.de.yml
db/migrate/20221216132621_add_address_to_schools.rb
db/schema.rb
spec/factories/schools.rb
spec/features/schools_spec.rb

Closes #106.
* Add address parameters to schools in database
* Add address parameters to form when creating new schools or editing them
* Add address and contact details to `schools#show`
* Add zip code and city to `schools#index`
* Homepage, e-mail and phone numbers are clickable
* Homepage is validated as suggested. If the user enters an URL without the protocol, we assume `https` and add that. So you can enter `example.com` and we store `https://example.com` (the validation gem requires a protocol).
* E-mail addresses are validated against Ruby's builtin regexp. That one is not very strict, but ensures that we have at least an `@` in it.
* Phone numbers are validated using Phony and are formatted when displayed.

Schools | Add address

---

app/controllers/schools_controller.rb
app/views/schools/_form.html.haml
app/views/schools/show.html.haml
config/locales/models.de.yml
db/migrate/20221216163532_add_federal_state_to_schools.rb
db/schema.rb

Closes #128.
Adds `federal_state` to schools. New form field when creating/editing, and display in the show view of the school.

Add `federal_state` to schools

---

app/helpers/version_helper.rb
app/models/school.rb
app/views/adjectives/show.html.haml
app/views/nouns/show.html.haml
app/views/schools/show.html.haml
app/views/shared/_versions.html.haml
app/views/verbs/show.html.haml
config/locales/views.de.yml
spec/features/nouns_spec.rb

Related to #106.
* Adds a paper trail to schools. Sorry, I missed that in the last PR.
* Refactors the `versions` partial to be independent of words. That is, we use the same partial to show changes in words and schools.

Add paper trail for schools

---

Gemfile
Gemfile.lock
app/controllers/concerns/word_filter.rb
app/views/shared/_filter.html.haml
spec/models/word_spec.rb

Closes #117.
This is a simple implementation of the requirement in #117. If you search for `kinder`, you'll now find `Kind` as well.
* The single filter fields of nouns, verbs and adjectives now use a "smart filter".
* The smart filter searches for different things and then justs `UNION`s them together into search results. It searches in:
* The base form of the word (aka `name`)
* The plural form of a noun
* The comparative or superlative form of an adjective
* The phonetic representation of the base form
* The power search page is unchanged. Entering a plural form of a noun there won't find anything.
* This is kind of a quick fix. It satisfies the requirement in #117. I'd suggest that we create a general concept about the search first (as in #67) before we invest more time in this.
* …

Plural search

---

spec/models/word_spec.rb

This fixes a spec where the expectation of an array is wrong. `match` is dependent on the order of the items in the array, whereas `match_array` is not. As we don't order it yet, this makes the spec stable.

Fix flaky spec as order does not matter

---

app/controllers/users/sessions_controller.rb
app/models/user.rb
config/initializers/devise.rb
db/migrate/20230203142751_add_confirmable_to_devise.rb
db/schema.rb
spec/factories/users.rb
spec/features/profile_spec.rb
spec/features/signup_spec.rb
spec/support/flows/signup.rb

Related to #154.
Add email confirmation:
* New users need to confirm their email address before they can sign in
* Existing users receive a confirmation email address when first accessing the app again. They also can't sign in until they have confirmed their email address.

Add email confirmation

---

app/assets/stylesheets/application.tailwind.css
app/controllers/learning_group_memberships_controller.rb
app/controllers/learning_groups/user_generations_controller.rb
app/models/ability.rb
app/models/user.rb
app/services/user_account_generator.rb
app/views/learning_group_memberships/reset_password.html.haml
app/views/learning_groups/show.html.haml
app/views/learning_groups/user_generations/create.html.haml
app/views/learning_groups/user_generations/new.html.haml
config/application.rb
config/locales/actions.de.yml
config/locales/views.de.yml
config/routes.rb
spec/features/user_generation_spec.rb

Related to #154
Adds generation of user accounts to a learning group. Also includes resetting of the password for generated accounts.

Add generation of user accounts

---

app/controllers/concerns/list_addable.rb
spec/features/filter_spec.rb

Potentially fixes some flaky specs.
The issue is that capybara doesn't wait for the Turbo requests firing while the user types. We now click on the hidden submit button (which exists for screen readers). Hopefully, this makes Capybara aware of the form submission and triggers it to wait accordingly.
The CI run through fine in the first attempt, but that's not really a proof that those specs are not flaky anymore.. :slightly_smiling_face: 
After merging this PR, we can rebase the existing PRs to have some more candidate runs.

Potentially fix a couple of flaky specs

---

.rubocop.yml

This adds a `rubocop.yml` to support Rubocop correctly in editors. Otherwise it uses the default Rubocop rules instead of the ones provided by `standardrb`, which makes editors show a lot of warnings.

Add Rubocop rules to support editors

---

app/views/application/_navigation.html.haml
config/locales/navigation.de.yml

Related to #170 
Replaces the logo in the navigation with text:

Replace logo in navigation with text

---

app/components/word_panel_component.html.haml
app/components/word_panel_component.rb
app/helpers/components_helper.rb
app/views/adjectives/_adjective.html.haml
app/views/function_words/_function_word.html.haml
app/views/nouns/_noun.html.haml
app/views/verbs/_verb.html.haml

Closes #176.
Changes the word panel layout:

Change word panel layout

---

app/assets/stylesheets/application.tailwind.css
app/components/omni_search_field_component.html.haml
app/components/word_panel_component.html.haml
app/controllers/application_controller.rb
app/controllers/searches_controller.rb
app/helpers/components_helper.rb
app/helpers/filter_helper.rb
app/views/filters/_form.html.haml
app/views/homes/_search_form.html.haml
app/views/layouts/application.html.haml
app/views/searches/show.html.haml
app/views/words/_index.html.haml
config/locales/views.de.yml
config/tailwind.config.js

Closes #171 and #188.
* Adapt search results page to better fit the new design
* Change breakpoints for search results. These depend on whether the filter is open or not. The GIFs are not completely up to date regarding design, but the grid and layout did not change.
With an open filter:
Without the filter:

Search results | Design and breakpoints

---

app/components/omni_search_field_component.rb
app/javascript/controllers/home_search_controller.js
app/views/homes/_search_form.html.haml
app/views/homes/show.html.haml

Closes #170.
This hides the logo when the user types in the search field on the homepage.
Originally in #170 this was supposed to only be done on mobiles. However, during testing I didn't dislike the effect on the desktop, especially on smaller laptops. @wintermeyer What do you think? Shall we limit the effect only to mobiles?

New search | Hide logo during search

---

README.md
app/jobs/tts_job.rb
app/models/word.rb
app/views/nouns/show.html.haml
app/views/words/_tts.html.haml
spec/jobs/tts_job_spec.rb
spec/models/word_spec.rb
spec/support/tts.rb

- Adds a hint to the README.md how to manually trigger a TTS Job for a word model.
- Adds a mention for example sentences to the README.md
- Adds the TTS generation for the example sentences to the TtsJob
- Refactoring to keep TtsJob DRY
- Extends the word model to have multiple audio files in a backwards compatible way
- Adds some helper methods to the word model to work with the audio attachments
- Extends the tts partial to support the example sentences
- Adds the tts partial to the example sentences of nouns (didn't found that for other words types?)
- Extends the RSpec for the TtsJob to cover example sentences
See #169

Feature 169: TTS for example sentences

---

app/views/searches/_mobile_word_type_filter.html.haml

Closes #196
The problem was that using the normal `merge` the param `filterrific[word_type]` was not correctly merged and hence appeared twice in the URL.

Fix word type filter on mobile

---

app/controllers/concerns/word_filter.rb
spec/models/word_spec.rb

Closes #208
* Removes whitespaces from beginning and end of the search query
* Coalesces whitespaces within the word to one. So when searching for `american   football`, we will search the database for `american football`.

Change to trim whitespaces

---

app/components/omni_search_field_component.html.haml
app/components/omni_search_field_component.rb
app/views/homes/_search_form.html.haml
app/views/homes/show.html.haml

Closes #195
Ensures the cursor doesn't jump in the search field while typing.

Fix cursor not moving on Turbo updates

---

app/javascript/controllers/home_search_controller.js
app/views/homes/show.html.haml

Closes #193 
Changes the logo on the homepage to only be removed on mobile devices.
Also instructed browsers to scroll smoothly, for those which support it.
[`scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) is used for the scrolling, which doesn't support much customizations. We do have to use it though as without it the input field is outside of the view to the top.
As an alternative, what about showing the input field at the top on mobiles from the beginning? The search results would then show above the logo.

Mobile | Logo removal on homepage

---

app/components/omni_search_field_component.html.haml
app/javascript/controllers/reset_search_controller.js

Closes #198
This fixes the search field to contain arbitrary old values.
The cause of this is `data-turbo-permanent` which makes the element sticky on the page. It will never be recreated when changing the page. This is great so that the cursor stays where it is. If we were to recreate the element, the cursor jumps to the beginning (happens while the user is typing).
The amazing thing is that those arbitrary values even survive hard refreshes of the browser. I assume that Turbo is caching the element somewhere. We therefore have to reset the value manually.
Before this change I was able to reproduce the issue with:
1. Enter something on the homepage
2. Hit enter to go to the search results page
3. Click on the logo on the top left
4. No results are shown. The input field still shows the …

Fix empty search field

---

app/views/homes/_search_result.html.haml

Closes #224
Adds a space between article and noun. Didn't include the polyfill as I understood that we don't include that now. If we encounter many users with old (not upgradable) iPads, we could still add it. Doesn't hurt that much.

Add space between article and noun

---

app/components/word_type_dropdown_item_component.html.haml

Remove hover for empty word type filters on mobile

---

app/components/highlighted_search_result_component.html.haml
app/components/highlighted_search_result_component.rb
app/views/homes/_search_result.html.haml
config/tailwind.config.js
spec/components/highlighted_search_result_component_spec.rb

Closes #194 
Adds highlights to the search results on the homepage. Unfortunately, this reverts the changes of #224. We now have multiple `span` tags for the different parts of the word (highlighted or not). We have to use `flex` there because otherwise we get spaces between the different word parts. We could ensure that there is no newline between the `span` tags, but that doesn't look that good in HAML.
I used the yellow from the design - in the GIF below the color appears too bright.

Add search highlights

---

app/views/searches/show.html.haml

Closes #230
Changes the filter width to be a bit wider.

Fix filter width on smaller desktops

---

app/helpers/filter_helper.rb

Closes #248
This fixes multi-select filters, such as `Phänomene`, `Strategien` or `Stichwörter`.

Fix multi-select filters

---

app/assets/stylesheets/application.tailwind.css
app/javascript/controllers/home_search_controller.js
app/views/homes/_search_result.html.haml

Closes #185
This adds cursor navigation in the search results. If a result is selected (highlighted in blue), pressing `enter` visits that word's page. If none is selected, enter shows the search results page.
It doesn't change the value in the search field as Google does it. That would be way more complex, because when we change the value in the input field, the search results will change as well, basically showing only that one word :slightly_smiling_face:

Add cursor navigation in search results

---

app/javascript/controllers/home_search_controller.js
app/views/homes/_search_form.html.haml

Related to #257
When hitting `enter` in the search field, two requests are made:
1. The first submits the form via the hidden screen reader submit button. That just displays the search results in the autocomplete.
2. The second wants to visit the page of the selected word
We should only make one request. This PR ensures that only one request is made.
Hopefully that fixes the issues on production as well.

Fix multiple requests being fired when hitting `enter`

---

app/models/word.rb
db/migrate/20221120163440_add_flash_cards_to_students.rb
db/migrate/20221202092420_add_example_sentences_to_words.rb
db/migrate/20221202144813_add_cologne_phonetics_to_words.rb

Closes #262
Fixes migrations so that the following works:
```
bin/rails db:create db:migrate
```

Fix migrations on empty database

---

app/views/layouts/application.html.haml
app/views/words/_tts.html.haml

Closes #228
The audio player not appearing on Safari is a Turbo problem (I assume). When Turbo is disabled the audio player is always displayed.
This PR proposes to disable Turbo on the word's detail page. This fixes the audio player not appearing on Safari (I can reproduce it on the iPad).
I haven't found any negative consequences of that change so far. Search etc. still seem to work.
I'll also try to reproduce it in a vanilla project in my off-time and check with Turbo if that is a bug or not.

Fix audio player not appearing on Safari

---

app/javascript/controllers/medium_controller.js
app/views/layouts/application.html.haml
app/views/words/_tts.html.haml

Related to #228.
Instead of disabling Turbo completely, this removes and re-adds the audio element. Tested on an iPad.

Change to use dfiferent Safari audio workaround

---

app/views/filters/_form.html.haml

Closes #232
This only shows viable options for the three select fields below. This also has the effect that options, which were created but are not used by any words, are also hidden now.
Hiding them was quicker to implement than showing them disabled. Let me know if you still want to see them instead and just gray them out.

Change select lists to only show available categories etc.

---

app/controllers/concerns/word_filter.rb
spec/models/word_spec.rb

Closes #277 
Search results after this change:

Fix sort order for 100% matches

---

app/views/homes/show.html.haml

Closes #290
Now the link opens the filter.

Fix link to open filter

---

app/views/words/_lists.html.haml

Closes #295
The box is now only shown when either the word is on lists or the user is logged in and has lists the word could be added to.

Fix hiding of word lists box when no lists are present

---

app/components/word_panel_component.html.haml

Closes #299
We showed the type of the word before, now its meaning.

Change sub title of search results to show meaning

---

app/components/highlighted_search_result_component.html.haml
app/components/highlighted_search_result_component.rb
app/models/noun.rb
app/models/word.rb
app/views/homes/_search_result.html.haml
config/locales/words.de.yml
spec/components/highlighted_search_result_component_spec.rb

Closes #289
Adds a more sophisticated display of the search hits if they are found in the plural, comparative or superlative.

Add more sophisticated display of search hits

---

app/components/word_panel_component.html.haml
app/components/word_panel_component.rb
app/views/flashcards/_word.html.haml

Closes #312
Changes word panels in Wörterklinik to use the same panel as in the search results.

Change to use generic word panel component

---

app/controllers/flashcards_controller.rb
app/views/flashcards/_tabs.html.haml
app/views/flashcards/_word.html.haml
app/views/flashcards/_words.html.haml
app/views/flashcards/index.html.haml
app/views/lists/move_word.turbo_stream.haml

Closes #313 
Changes the display of flashcards to tabs. When moving words, there is now no confetti animation anymore, because the moved word is not visible anymore after moving.

Wörterklinik | Tabs

---

app/models/noun.rb
app/views/nouns/show.html.haml

Closes #309
Now shows the article in front of the plural form.

Change to show plural with article

---

app/components/highlighted_search_result_component.html.haml
app/components/highlighted_search_result_component.rb
app/components/word_panel_component.html.haml
app/components/word_panel_component.rb
app/views/words/_index.html.haml

Closes #315 and #316
Adds search highlights also to the search page and adds the extensions from the homepage (like "Plural von das Kind").

Add search highlights on search page

---

app/components/highlighted_search_result_component.html.haml
app/components/highlighted_search_result_component.rb
app/components/word_panel_component.html.haml
app/components/word_panel_component.rb
app/controllers/concerns/word_filter.rb
app/views/words/_index.html.haml
spec/features/filter_spec.rb

Closes #314
Adds phonetic search to the main search (sorted at the end of the results).

Add cologne phonetics back to main search

---

app/components/omni_search_field_component.html.haml
app/controllers/concerns/word_filter.rb
app/helpers/filter_helper.rb

Closes #339.
Fixes cursor focus moving back to main search field when entering text somewhere else.
* This loses autofocus on the advanced search page. The autofocus caused the loss of the focus when the search results are refreshed. If this is an issue, we could add some JavaScript which checks whether the focus is set in an input field, and if not, only then focus the main search field.

Search | Fix cursor focus

---

app/views/filters/_form.html.haml

Closes #340.
Changes the consonant/vowel input field to only accept `KVkv`.

Change to restrict input to only accept `[KVkv]`

---

app/components/omni_search_field_component.html.haml
app/components/omni_search_field_component.rb

Closes #342.
This possibly fixes flashing text in the search input field of the homepage. I have seen this happening before, but couldn't reliably reproduce it, so I'm not 100% sure whether this fixes the issue.

Possibly fix flashing values in the homepage search field

---

app/helpers/filter_helper.rb

Closes #351
Changes to make the keyword input field permanent, so that it doesn't lose focuse on updates.

Fix cursor focus when changing keywords

---

Gemfile
Gemfile.lock

`better_errors` has been updated and fixed the development startup of the Rails server.
cf. https://github.com/BetterErrors/better_errors/issues/516

Fix rails development startup regarding better_errors

---

app/controllers/learning_group_memberships/requests_controller.rb
app/controllers/learning_groups/user_generations_controller.rb
app/models/learning_group_membership.rb
app/services/flashcards.rb
spec/features/flashcards_spec.rb

Closes #317.
* When adding a user to a learning group, that user will receive all words from the group.
* When removing a user from a learning group, all words of that group will be removed from the user. Except words which are also present in other groups the user belongs to.
* When generating user accounts in a learning group, all users now receive all words from the group.

Wörterklinik | Add/Remove words when adding/removing users to/from a learning group

---

app/helpers/filter_helper.rb
app/views/filters/_form.html.haml
app/views/filters/_hierarchies.html.haml
app/views/filters/_keywords.html.haml
app/views/filters/_sources.html.haml
app/views/filters/_topics.html.haml
app/views/searches/_omni_search.html.haml
app/views/searches/_open_advanced_link.html.haml
app/views/searches/show.turbo_stream.haml

This should fix #351 again. That is, focus should be kept while searching.
The problem was that all advanced filters were rendered again when the filters changed. Now we only render the elements again which change (topics, hierarchies, etc.).

Filter | Loss of focus

---

app/controllers/concerns/word_filter.rb

Closes #442 
Fixes the following error:
```
ActiveRecord::StatementInvalid - PG::AmbiguousColumn: ERROR:  column reference "name" is ambiguous
LINE 1: ... "topics"."id" = "topics_words"."topic_id" WHERE (name ~* '(...
```

Fix ambiguous column error

---

config/deploy.rb

Related to #444.
This fixes unicorn and the background jobs to read the `SECRET_KEY_BASE` correctly. We need to inject an environment file to both services.
I already deployed these changes manually, which worked fine.

Fix presence of `.env` file and passing env variables to `bundle`

---

app/views/filters/_keywords.html.haml

Closes #437
This fixes the inital display of the **keywords** in the search. We only want to show used keywords, not all words.

Fix initial display of only used keywords

---

app/views/filters/_form.html.haml
config/locales/filter.de.yml
spec/features/filter_spec.rb

Closes #435
Adds a button to reset everything in the filter:

Add reset filter button

---

app/assets/images/montessori/adjektiv.svg
app/assets/images/montessori/artikel.svg
app/assets/images/montessori/hilfsverb.svg
app/assets/images/montessori/konjunktion.svg
app/assets/images/montessori/nomen.svg
app/assets/images/montessori/praeposition.svg
app/assets/images/montessori/pronomen.svg
app/assets/images/montessori/verb.svg
app/assets/stylesheets/application.tailwind.css
app/assets/stylesheets/components/word_header.css
app/assets/stylesheets/components/word_symbol.css
app/components/word_header_component.html.haml
app/components/word_header_component.rb
app/views/nouns/show.html.haml
app/views/words/_tts.html.haml

Closes #113.
Adds the Montessori symbols for nouns, verbs and adjectives.
Also changes the mobile layout to show some properties in a grey block, including the Montessori symbol.

Detail page | Montessori symbols

---

app/components/word_header_component.html.haml
app/controllers/strategies_controller.rb
app/models/strategy.rb
app/views/strategies/_form.html.haml
app/views/strategies/_strategy.html.haml
app/views/strategies/show.html.haml
config/locales/models.de.yml

Closes #114.
- Add image upload to strategies
- Add display of strategies on the word

Detail page | Fresch symbols

---

app/controllers/concerns/open_graph.rb
app/models/word.rb

Closes #301
This adds twitter card meta tags. We already had open graph tags, so most other apps should already have helpful information to render a preview.
It also changes the image size to comply with more modern sizes.

Twitter cards

---

app/components/box_description_list.rb
app/components/box_description_list_item_component.rb
app/controllers/word_view_settings_controller.rb
app/models/ability.rb
app/models/word_view_setting.rb
app/views/pages/navigation.html.haml
app/views/word_view_settings/_form.html.haml
app/views/word_view_settings/_word_view_setting.html.haml
app/views/word_view_settings/edit.html.haml
app/views/word_view_settings/index.html.haml
app/views/word_view_settings/new.html.haml
app/views/word_view_settings/show.html.haml
config/locales/enumerize.de.yml
config/locales/models.de.yml
config/locales/views.de.yml
config/routes.rb
db/migrate/20240615153651_create_word_view_settings.rb
db/schema.rb
spec/factories/word_view_settings.rb
spec/features/word_view_settings_spec.rb

Related to #440.
This adds a `WordViewSetting` model and CRUD for it. It will later be used to steer the view of words. Such as, shall we display syllable arcs or not.
The model is currently not yet used. This PR only adds CRUD for it.

Word view settings

---

app/components/word_header_component.html.haml
app/controllers/word_view_settings_controller.rb
app/models/genus.rb
app/models/word_view_setting.rb
app/services/word_types.rb
app/views/nouns/show.html.haml
app/views/word_view_settings/_form.html.haml
app/views/word_view_settings/show.html.haml
config/locales/models.de.yml
db/migrate/20240616152222_add_wording_to_word_view_settings.rb
db/schema.rb

Related to #440
This adds different wording for word types and genus.
These can be selected as view settings:
They are then reflected when rendering the word:

Add different wording for word types and genus

---

app/views/themes/default_adjective.liquid
app/views/themes/default_noun.liquid
app/views/themes/default_verb.liquid

Closes #493.
Fixes the display of the "show" views. Already deployed the branch so the words are shown correctly again.
My bad: I believed to remember that there is an `erb` helper to render ERB files (in truth that only exists in Sinatra). And yes, that worked in development, but not in production.
Turns out, Mina has defined a helper `erb`, doing what I expect it to do. They extend that helper onto `Object`, so that was magically available everywhere. As we don't load that helper in production, the method was missing.

Fix missing `erb` helper in production

---

app/controllers/hierarchies_controller.rb
app/models/ability.rb
app/models/hierarchy.rb
app/views/hierarchies/_form.html.haml
app/views/hierarchies/_hierarchy.html.haml
app/views/hierarchies/show.html.haml
app/views/pages/navigation.html.haml
config/locales/models.de.yml
config/locales/views.de.yml
config/routes.rb

Closes #492.
Changes the existing hierarchy views to be publicly available. Also adds images to hierarchies.

Hierarchy list

---

app/views/adjectives/_form.html.haml
app/views/function_words/_form.html.haml
app/views/nouns/_form.html.haml
app/views/verbs/_form.html.haml

Related to #440
This fixes the display after saving a word. Previously, the form did not disappear and was overlapped with the show view.

Fix display after saving word

---

app/controllers/concerns/word_filter.rb
app/controllers/searches_controller.rb

Closes #501
This adds a filter to search for empty syllables. As soon as deployed, the following link shows all words without syllables:
https://wort.schule/seite/search?filterrific[filter_syllables_empty]=1
Note that the filter is not part of the form. As soon as you click any other filter (even a different word type), you lose the syllables filter. You would then need to manually add `filterrific[filter_syllables_empty]=1` to the URL.

Filter | Empty syllables

---

app/components/word_type_filter_component.rb
app/helpers/word_view_settings_helper.rb
app/services/word_types.rb
app/views/homes/_search_result.html.haml
app/views/searches/_word_type_filter.html.haml
config/locales/filter.de.yml
spec/features/filter_spec.rb

Closes #495.
This changes the wording of word types to the configured ones, also in the search:

Wording | Word types

---

app/controllers/word_view_settings_controller.rb
app/helpers/word_view_settings_helper.rb
app/models/word_view_setting.rb
app/services/numerus.rb
app/services/theme_variables.rb
app/views/nouns/_header.html.haml
app/views/themes/default_noun.liquid
app/views/themes/default_verb.liquid
app/views/word_view_settings/_form.html.haml
app/views/word_view_settings/show.html.haml
config/locales/models.de.yml
config/locales/themes.de.yml
db/migrate/20240630150641_add_numerus_wording_to_word_view_settings.rb
db/schema.rb

Closes #111.
Adds an option for the wording of singular/plural.
Depending on what is selected in the view settings, we then show either `Singular/Plural` or `Einzahl/Mehrzahl`.

Wording | Singular/plural

---

app/views/themes/default_noun.liquid
app/views/themes/default_verb.liquid
app/views/themes/liquid/meaning.liquid
app/views/themes/liquid/relations.liquid

Closes #507
In liquid there is no `||`, we have to use `or` instead.

Fix display of boxes

---

app/views/word_view_settings/show.html.haml
config/locales/views.de.yml

Closes #508
Adds the link and explanation on how to use the word view setting link.

Add hint about link to word view setting

---

app/controllers/hierarchies_controller.rb
app/controllers/keywords_controller.rb
app/helpers/components_helper.rb
app/views/hierarchies/index.html.haml
app/views/keywords/index.html.haml
app/views/keywords/show.html.haml
config/locales/views.de.yml
config/routes.rb

Closes #492.
- Hierarchies now have a button to show/hide children
- Change behavior of the keywords page: you can now select multiple keywords and it only shows words which have all those keywords.
- Related keywords are now shown correctly

Keywords | Behavior

---

app/models/ability.rb

Closes #516
This fixes links as https://wort.schule/?word_view_setting_id=1 for users who are not logged in.
We authorize the view settings, which is in general a good idea. I just forgot to allow access to public view settings to everyone.

Fix access to word view settings for guests

---

app/components/syllables_component.html.haml
app/components/syllables_component.rb
app/components/word_header_component.html.haml
app/views/adjectives/_header.html.haml
app/views/function_words/_header.html.haml
app/views/nouns/_header.html.haml

Closes #521
Removes the duplicate word names we had in the header (once normal and once syllables):
If there are no syllables:

Change word header to contain word only once

---

app/views/verbs/_header.html.haml

Fix duplicate words in header of verbs

---

app/assets/stylesheets/application.tailwind.css
app/assets/stylesheets/form.css
app/components/user_profile_attributes_component.html.haml
app/controllers/profiles_controller.rb
app/controllers/reviews_controller.rb
app/helpers/word_helper.rb
app/models/concerns/reviewable.rb
app/models/user.rb
app/services/llm/attributes.rb
app/views/profiles/edit.html.haml
config/locales/models.de.yml
db/migrate/20241115170537_add_review_attributes_to_users.rb
db/schema.rb
spec/features/reviews_spec.rb
spec/models/word_attribute_edit_spec.rb

This allows a user to set the word attributes which should appear in the review.
The user then only sees reviews regarding those attributes.

Review | Select which attributes to review

---

app/services/llm/invoke.rb
config/initializers/open_ai.rb

Adds a default value for the ollama URL because the instructor gem does not seem to have that default. Also sets a retry and a mode parameter, which hopefully improves the responses (they currently fail sometimes due to an unexpected response).

Add default value for ollama URL

---

app/components/user_profile_attributes_component.html.haml
app/models/word_attribute_edit.rb
app/models/word_import.rb
app/services/import/word.rb
app/services/llm/enrich.rb
db/migrate/20241116185919_create_word_imports.rb
db/migrate/20241116200912_add_errors_to_word_imports.rb
db/schema.rb
spec/factories/word_imports.rb
spec/rails_helper.rb
spec/services/import/word_spec.rb

This adds a couple of improvements:
- Do not store empty proposals for attributes from LLM responses
- Fix migration exception when using generators
- Add `WordImport` model to store words which are imported. If the word is already known, the LLM enrichment for that word will be run
- Add edit button for review attributes

LLM improvements

---

app/components/word_panel_component.html.haml
app/components/word_panel_component.rb
app/helpers/word_helper.rb
app/views/adjectives/_adjective.html.haml
app/views/function_words/_function_word.html.haml
app/views/nouns/_noun.html.haml
app/views/reviews/show.html.haml
app/views/verbs/_verb.html.haml

This adds the topics below the word, when the word has no "meaning" set. If it has, the meaning is shown instead.
New words are imported with a topic, so for those we can show the topic.

Review | Topics in words partial

---

app/components/reviews/new_word_component.html.haml
app/controllers/reviews_controller.rb
app/mailers/review_mailer.rb
app/models/change_group.rb
app/models/review.rb
app/views/reviews_mailer/discarded.html.haml
config/locales/mailers.de.yml
config/locales/views.de.yml
spec/features/reviews/new_word_spec.rb

This allows a new word in the review to be discarded. We then send an email to the environment variable specified in `REVIEW_EXCEPTION_MAIL`.

LLM | Discard new word

---

app/services/llm/invoke.rb
config/deploy.rb
config/initializers/langchain.rb

A couple of fixes regarding the LLM setup:
1. Add default ollama URL, if not set via the environment
2. Increased timeout of LLM calls as the default timeout of 60 seconds is not enough on the server (also not locally) for our current prompt
3. Add restart of jobs service after deployment

LLM setup fixes

---

app/jobs/enrich_word_job.rb
app/jobs/import_word_job.rb
config/application.rb
config/initializers/langchain.rb

Adds its own job queue for the LLM so that we don't schedule more than one LLM job at the time. Also increases the LLM timeout, because it already took 9min on the server, so 10min might cut it a bit close.

Queues for LLM

---

app/services/llm/enrich.rb
app/services/llm/invoke.rb
app/services/llm/schema/base.rb

Changes the LLM prompt and also removes the JSON schema from it. My suspicion is that the JSON schema confuses more than it helps. I get better usable results without it with llama3.1.

Remove JSON schema from LLM request

---

app/components/reviews/llm_value_component.html.haml
app/components/reviews/llm_value_component.rb
app/models/word_attribute_edit.rb
app/services/llm/attributes.rb
app/services/llm/enrich.rb
app/services/llm/schema/shared.rb
app/views/reviews/_word_attribute_edits.html.haml
config/locales/models.de.yml
spec/factories/compound_entity.rb
spec/services/llm/enrich_spec.rb

Various bug fixes:
- In some situations, empty array responses by the LLM created a review
- Adds missing translations for verb properties
- Booleans are now displayed as "Ja / Nein" in the review instead of "true / false"
- Fix review of compound entities
- Fix review of example sentences

LLM | Various bug fixes

---

app/components/reviews/llm_value_component.rb

This fixes suggestions to be sorted within the autocomplete:

Change suggestions to be sorted

---

app/views/words/_tts.html.haml

Closes #650.
Chrome doesn't seem to render audio players with `width: auto` anymore.

Fix display of audio player in Chrome

---

app/components/reviews/llm_value_component.html.haml
app/javascript/controllers/toggle_buttons_controller.js
app/models/concerns/reviewable.rb
app/services/llm/enrich.rb
app/services/llm/invoke.rb
app/services/llm/schema/shared.rb
config/locales/components.de.yml
config/locales/models.de.yml
spec/features/reviews/word_attribute_edit_spec.rb
spec/features/themes_spec.rb
spec/services/llm/enrich_spec.rb

We still need the `keywords` property in the `Word` schemas for proper parsing of the results and comparison to the current values. Also it's otherwise missing in the selection in the profile.
Also adds a missing translation and fixes a flaky spec.

Fix review of keywords

---

app/controllers/reviews_controller.rb
app/models/new_word.rb
app/models/unlisted_keyword.rb
app/services/import/word.rb
app/services/llm/attributes.rb
db/migrate/20250225212139_create_unlisted_keywords.rb
db/schema.rb
spec/features/reviews/unlisted_keywords_spec.rb

Closes #658.
Based on #657.
This adds "unlisted keywords". When a keyword is proposed by the LLM not yet found in the database, an "unlisted keyword" is created. After that it is passed through the existing "new word" process. So the word is checked by the LLM for base form and word type. If that succeeds, it has to be reviewed by a human (to either be added to the database or discarded).
If the new word is approved by a human, it is added to the database. We then check the unlisted keywords and add all pending as keywords to the original words.

Add unlisted keywords

---

app/models/change_group.rb
app/services/llm/enrich.rb

Closes #672.
In the review the attributes are currently not sorted. This PR introduces sorting based on the order of the grouped attributes in the code.

Review | Sort attributes

---

app/services/llm/enrich.rb
app/services/llm/invoke.rb

Closes #673.
Adds two new variables for the LLM prompt:
1. `{meaning}`:
2. `{topics}` (comma separated):
cc @frankjmueller

LLM prompt | Add `meaning` and `topics` to template

---

app/components/reviews/llm_value_component.rb
app/javascript/controllers/toggle_buttons_controller.js
app/models/genus.rb
app/models/hierarchy.rb
app/models/phenomenon.rb
app/models/postfix.rb
app/models/prefix.rb
app/models/strategy.rb
app/models/topic.rb
app/models/word.rb
app/services/llm/attributes.rb
config/application.rb
spec/features/reviews/keywords_spec.rb
spec/features/reviews/unlisted_keywords_spec.rb
spec/services/llm/attributes_spec.rb
spec/services/llm/enrich_spec.rb

Closes #676.
This adds distinction of different words to keywords found by the LLM. If the LLM proposed `Spielen`, it returns `spielen` and `Spielen`. The human reviewers can then choose the fitting ones.

Reviews | Find all existing keywords

---

app/components/reviews/llm_value_component.rb
app/javascript/controllers/toggle_buttons_controller.js

Closes #694.
- Changes keywords to be shown in bold font in review
- The multi-select is now cleared when a value has been selected

Review | Keyword improvements

---

app/components/theme_component.html.haml
spec/support/crud.rb

Closes #696.
Adds a second edit button:

Word pages | Second edit button

---

db/migrate/20230823174305_change_cologne_phonetics_to_array.rb
db/migrate/20241117164500_create_new_words.rb
db/migrate/20241122182419_create_change_groups.rb

Closes #705.
Should fix running migrations on an empty database.

Fix migrations
