wort-schule/wort.schule

.github/workflows/run_tests.yml, app/decorators/page_decorator.rb, config/deploy.rb, config/initializers/friendly_id.rb, spec/decorators/page_decorator_spec.rb, spec/requests/page_spec.rb, spec/support/open_graph_matcher.rb
Fixes #42.
* Fix shadow warning
* Fix some other linter issues
* Fix CI to fail on all linting issues (not just on "uncorrectable")
=> Fix lint issues

app/models/word.rb, app/views/adjectives/show.html.haml, app/views/function_words/show.html.haml, app/views/nouns/show.html.haml, app/views/verbs/show.html.haml, app/views/words/_more_meanings.html.haml, config/locales/views.de.yml, spec/features/nouns_spec.rb, spec/models/word_spec.rb
Closes #33.
* Add a link in the top right if there are more words with the same spelling. Link goes to the search form.
=> Add link to more meanings

app/controllers/lists_controller.rb, app/models/ability.rb, app/models/list.rb, app/models/word.rb, app/views/application/_main_menu.html.haml, app/views/lists/_form.html.haml, app/views/lists/_list.html.haml, app/views/lists/edit.html.haml, app/views/lists/index.html.haml, app/views/lists/new.html.haml, app/views/lists/show.html.haml, app/views/words/_general.html.haml, app/views/words/_lists.html.haml, config/locales/enumerize.de.yml, config/locales/models.de.yml, config/locales/views.de.yml, config/routes.rb, db/migrate/20221007101443_create_lists.rb, db/migrate/20221007105111_create_join_table_lists_words.rb, db/schema.rb, spec/factories/lists.rb, spec/features/lists_spec.rb
This adds basic functionality for word lists. Related to #16. More features for word lists will come later.
* Adds CRUD for word lists
* Shows words in list and allows to remove them
* When showing a word, shows the lists the word appears on and allows to add this word to a list.
=> Word lists

app/assets/stylesheets/application.tailwind.css, app/controllers/flashcards_controller.rb, app/controllers/learning_pleas_controller.rb, app/controllers/lists_controller.rb, app/javascript/controllers/flashcard_drag_controller.js, app/models/ability.rb, app/models/list.rb, app/models/student.rb, app/models/user.rb, app/services/flashcards.rb, app/views/application/_main_menu.html.haml, app/views/flashcards/index.html.haml, config/locales/models.de.yml, config/locales/views.de.yml, config/routes.rb, db/migrate/20221116190044_add_flashcard_section_to_lists.rb, db/schema.rb, spec/features/flashcards_spec.rb
Related to #16.
This just implements the very basics. There are a lot of things which are still unfinished.
It would be great to get some feedback on it though. Let's afterwards discuss what is missing and prioritze it.
* When adding a word list to a learning group, all words of that list are now added to the first section of the student's word list
* Added a view of all word lists to learn. Able to drag and drop words from one list to another.
=> Wörterklinik | Basics

db/migrate/20221120163440_add_flash_cards_to_students.rb, db/schema.rb
Related to #16.
This adds flashcard lists to existing students, if there are any.
=> Wörterklinik | Add flash card lists to existing students

app/views/filters/_add_to_list.html.haml
=> Fix display of 'add word to list' for unauthorized users

app/helpers/word_helper.rb, app/views/flashcards/_word.html.haml, app/views/lists/show.html.haml
Closes #76.
* Adds article to Wörterklinik
* Adds article to word lists
=> Add missing articles for nouns

app/views/application/_desktop_user_menu.html.haml, app/views/application/_main_menu.html.haml, app/views/example_sentences/_form.html.haml, app/views/filters/_form.html.haml, app/views/shared/_filter.html.haml, app/views/words/_versions.html.haml
Fixes #85.
After upgrade to Heroicon 1, some icons changed their names. I now checked all of them and corrected them.
=> Fix icons after upgrade of heroicon

config/application.rb, config/initializers/route_downcaser.rb, config/routes.rb, spec/features/nouns_spec.rb
This frees the word URLs like `/adler` not to clash with the application.
Not sure if we still want that. Feel free to approve or close :slightly_smiling_face: 
Related to #24.
=> Move the application below the namespace `/seite`

spec/features/filter_spec.rb
Potentially closes #102.
This potentially fixes a couple of flaky specs on the CI. Locally, they only fail 2 out of 30 times when only one flaky test is being run. The whole test suite passes fine for me locally.
With these changes, they never fail for me locally and the CI now also passed on the first try. Let's continue monitoring..
=> Potentially fix flaky specs

app/views/flashcards/_word.html.haml
Closes #104.
* Fix click on indicator to also show menu
* Fix width of buttons in card to always span the whole width of the card.
=> Wörterklinik | Fix clickable indicator

spec/features/filter_spec.rb
Fixes another flaky filter spec. Also replaces hardcoded German with proper translation.
=> Potentially fix another flaky filter spec

Gemfile, Gemfile.lock, app/controllers/adjectives_controller.rb, app/controllers/function_words_controller.rb, app/controllers/nouns_controller.rb, app/controllers/verbs_controller.rb, app/models/word.rb, db/migrate/20221206090348_add_hit_counter_to_words.rb, db/schema.rb, spec/features/nouns_spec.rb
Closes #91.
Adds `Word#hit_counter` which increases once every 24 hours. Known bots are ignored.
=> Word hit counter

app/views/application/_footer.html.erb
=> Add wiki link to footer

app/assets/stylesheets/application.tailwind.css, app/controllers/learning_group_memberships_controller.rb, app/models/ability.rb, app/models/learning_group.rb, app/models/learning_group_membership.rb, app/views/learning_groups/show.html.haml, config/locales/views.de.yml, config/routes.rb, db/migrate/20230203150017_add_role_to_learning_group_memberships.rb, db/schema.rb
Related to #154.
Adds group admins to learning groups.
=> Add group admin for a learning group

app/views/homes/_search_form.html.haml
Closes #175
This disables autocomplete in the new search field.
=> Disable autocomplete

app/components/omni_search_field_component.html.haml, app/components/omni_search_field_component.rb, app/views/filters/_form.html.haml, app/views/homes/_search_form.html.haml, spec/features/filter_spec.rb
Related to #171 
Adds the "omni" search field to the search page:
=> New search | Add omni search field

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/components/tabbed_radio_buttons.css, app/controllers/searches_controller.rb, app/helpers/filter_helper.rb, app/views/filters/_add_to_list.html.haml, app/views/filters/_form.html.haml, app/views/searches/show.html.haml, app/views/words/_index.html.haml, config/locales/filter.de.yml, spec/features/filter_spec.rb, spec/support/i18n_helpers.rb
Related to #171 
This changes the layout of the search page. Design and layout is not completely done yet, but it should be functionally complete.
=> New search | Search page layout

app/views/homes/_search_form.html.haml, app/views/homes/show.html.haml, app/views/layouts/application.html.haml, app/views/searches/_desktop_word_type_filter.html.haml, app/views/searches/_mobile_word_type_filter.html.haml, app/views/searches/show.html.haml, config/locales/filter.de.yml
Closes #187.
* Improves the word type filter on mobile.
* Improves the design of the search results on the homepage.
=> New search | Mobile layout

app/components/word_type_dropdown_item_component.html.haml, app/components/word_type_dropdown_item_component.rb, app/views/searches/_mobile_word_type_filter.html.haml, config/locales/filter.de.yml
Closes #200 
- Tasks from #200 
- Refactored the dropdown item links into a component so that the logic is readable
=> Mobile word type filter improvements

app/views/pages/navigation.html.haml
Closes #201 
Adds links to create new words:
=> Add "new" links

app/views/adjectives/_form.html.haml, app/views/adjectives/show.html.haml, app/views/example_sentences/_list.html.haml, app/views/nouns/show.html.haml, app/views/verbs/_form.html.haml, app/views/verbs/show.html.haml
- Extracts a partial for the example sentences part of the show view.
- Adds the example sentences to the form and show views of verbs and adjectives too.
=> Feature 186: Example sentences for adjectives and verbs

app/controllers/seo_controller.rb, app/views/seo/word_index.html.haml, config/locales/views.de.yml
- Fixes missing articles for noun cases
- Fixes missing translations for noun cases
- Fixes text color of word types in word index
=> Fix #223: Several Word Index fixes

config/locales/views.de.yml
=> fix: wrong i18n keys

app/components/word_type_filter_component.html.haml, app/components/word_type_filter_component.rb, app/views/searches/_desktop_word_type_filter.html.haml
=> Disable empty word type filters

app/views/application/_mobile_menu.html.haml, app/views/application/_navigation.html.haml
=> Change mobile menu not to show hamburger menu for guests

app/javascript/controllers/home_search_controller.js
Hopefully closes #246
Only goes to search page when there is a search term present.
=> Change not to go to search results page for empty

Gemfile.lock, app/views/homes/show.html.haml, config/locales/components.de.yml, config/locales/views.de.yml
* Fixes the tooltip of the search button (before it said "translation missing")
* Upgrade `turbo-rails`
=> Fix search title

app/views/seo/word_index.html.haml
For a screenshot, see https://github.com/wort-schule/wort.schule/issues/226#issuecomment-1453612280
=> Fix: Word Index beauty fixes

app/views/seo/word_index.html.haml
=> Fix: Padding of Word Index List

app/views/homes/_search_result.html.haml
Possibly fixes #257 
Unfortunately I can't reproduce it locally. It works just fine. I implemented my hunch what I believe should fix it. No idea why it works in development though.
=> Possibly fix `content missing` when opening search result

public/robots.txt
Closes #268
Adapts `robots.txt`.
=> Change search to be ignored by robots

app/assets/stylesheets/application.tailwind.css, app/helpers/filter_helper.rb
=> Change empty filter select fields to be disabled

app/controllers/concerns/word_filter.rb, spec/models/word_spec.rb
Closes #277.
Implemented as proposed:
=> Change sort weights to include plural forms etc. at beginning

app/views/homes/show.html.haml, config/locales/views.de.yml
=> Add button to advanced search

app/controllers/concerns/word_filter.rb, spec/features/filter_spec.rb, spec/models/word_spec.rb
=> Change phonetic to search only for exact matches

app/components/highlighted_search_result_component.html.haml, app/components/omni_search_field_component.html.haml, app/components/omni_search_field_component.rb, app/controllers/concerns/word_filter.rb, app/controllers/homes_controller.rb, app/controllers/searches_controller.rb, app/helpers/word_helper.rb, app/views/homes/_search_form.html.haml, app/views/searches/_mobile_word_type_filter.html.haml, app/views/searches/show.html.haml, spec/features/filter_spec.rb
Closes #300
Fixes keyword search in combination with a search term in the main search field.
=> Fix keyword search

app/components/omni_search_field_component.html.haml, app/components/omni_search_field_component.rb, app/views/application/_navigation.html.haml
Closes #342
Second try to fix old values appearing in the search field.
=> Possibly fix flashing in search field

Gemfile, Gemfile.lock
Fixes starting the Rails server in development.
cf. https://github.com/BetterErrors/better_errors/issues/516
=> Fix development startup

app/models/verb.rb, app/models/word.rb, db/migrate/20230825055433_redo_cologne_phonetics_for_verbs.rb, db/schema.rb, spec/models/word_spec.rb
- Add more verb forms to cologne phonetics
- Fix storing only unique cologne phonetics
=> Verbs | More forms for cologne phonetics

db/migrate/20231009165001_create_good_job_settings.rb, db/migrate/20231009165002_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb, db/migrate/20231009165003_create_good_job_batches.rb, db/migrate/20231009165004_create_good_job_executions.rb, db/migrate/20231009165005_create_good_jobs_error_event.rb, db/schema.rb
Updates the outdated good_job database schema.
=> Update good_job database schema

spec/rails_helper.rb
Fixes a deprecation after the Rails 7.1 update.
=> Fix fixture path deprecation

app/controllers/concerns/word_filter.rb, app/controllers/searches_controller.rb, app/views/filters/_form.html.haml, config/locales/filter.de.yml, spec/models/word_spec.rb
Closes #441 and #457.
- Add filter for letter count
- Add filter for syllables count
- Move keyword filter up
- Remove syllable filter
=> Filters | Letter/Syllables count

app/jobs/tts_job.rb, app/models/word.rb, spec/jobs/tts_job_spec.rb
Closes #434.
- Fix update of audio when the word is changed
- Fix invoking of the TTS job also when the genus of a noun is changed (we include the article in the audio)
=> Fix update of audio

Gemfile, Gemfile.lock, config/deploy.rb
Closes #461
Changes to use puma instead of unicorn in production. Fixes #461.
=> Change from unicorn to puma

app/components/user_profile_attributes_component.html.haml, app/controllers/adjectives_controller.rb, app/controllers/application_controller.rb, app/controllers/function_words_controller.rb, app/controllers/learning_groups_controller.rb, app/controllers/nouns_controller.rb, app/controllers/verbs_controller.rb, app/helpers/word_view_settings_helper.rb, app/models/ability.rb, app/models/learning_group.rb, app/models/user.rb, app/models/word_view_setting.rb, app/views/learning_groups/_form.html.haml, app/views/profiles/edit.html.haml, app/views/profiles/show.html.haml, app/views/word_view_settings/show.html.haml, config/locales/models.de.yml, config/locales/views.de.yml, config/routes.rb, db/migrate/20240616094413_migrate_word_view_settings.rb, db/migrate/20240616113721_migrate_word_view_settings_on_users.rb, db/migrate/20240616131957_remove_themes_from_learning_groups.rb, db/schema.rb, spec/features/themes_spec.rb
Related to #440.
This changes the `LearningGroup` and `User` to have a reference to `WordViewSetting` instead of the themes.
It also allows to set the view settings via URL: `/seite/ansicht/2`.
=> Use `WordViewSetting`

app/components/syllables_component.html.haml, app/components/syllables_component.rb, app/components/word_header_component.html.haml, app/controllers/word_view_settings_controller.rb, app/views/application/_word_font.html.haml, app/views/nouns/show.html.haml, app/views/word_view_settings/_form.html.haml, app/views/word_view_settings/show.html.haml, app/views/words/_syntax.html.haml, config/locales/models.de.yml, db/migrate/20240616133652_add_more_params_to_word_view_settings.rb, db/schema.rb
Related to #440.
This adds more view settings:
- Show/Hide house
- Show/Hide syllable arcs
- Color syllables or keep them black
- Show horizontal lines
- Show Montessori symbols
- Show Fresch symbols
- Show genus symbols
=> More view settings

app/components/word_panel_component.html.haml, app/components/word_panel_component.rb, app/controllers/keywords_controller.rb, app/controllers/profiles_controller.rb, app/models/ability.rb, app/models/keyword.rb, app/views/keywords/index.html.haml, app/views/keywords/show.html.haml, app/views/pages/navigation.html.haml, config/locales/models.de.yml, config/locales/views.de.yml, config/routes.rb
Related to #492.
This adds a list of all keywords. When clicking on a keyword, it shows related keywords and all words of that selected keyword.
=> Keyword list

app/services/word_types.rb, app/views/themes/liquid/syntax.liquid, config/locales/models.de.yml
=> Small fixes

app/models/hierarchy.rb, spec/models/hierarchy_spec.rb, spec/spec_helper.rb
=> Fix deletion of hierarchies

app/components/syllables_component.html.haml, app/components/syllables_component.rb, app/components/word_header_component.html.haml, app/helpers/font_helper.rb, app/helpers/word_view_settings_helper.rb, app/models/ability.rb, app/models/user.rb, app/services/fonts.rb, app/views/adjectives/_header.html.haml, app/views/application/_word_font.html.haml, app/views/function_words/_header.html.haml, app/views/nouns/_header.html.haml, app/views/verbs/_header.html.haml, app/views/word_view_settings/_form.html.haml
Closes #517
This got broken with the new "word view settings". Consolidated it now, so that the font is always taken from the view settings.
=> Fix rendering of custom font

app/controllers/keywords_controller.rb
Closes #525.
- Related keywords are now also sorted by word count
- Pagination of related keywords is reduced to only show 12 at once
=> Keywords | Order and max items

app/controllers/topics_controller.rb, app/models/ability.rb, app/models/topic.rb, app/views/hierarchies/index.html.haml, app/views/topics/_form.html.haml, app/views/topics/_topic.html.haml, app/views/topics/index.html.haml, app/views/topics/show.html.haml, config/locales/views.de.yml, config/routes.rb
Related to #532.
Changes the topics overview similar to the hierarchies overview.
=> Topic overview

Gemfile, Gemfile.lock, app/jobs/invoke_rake_task_job.rb, config/application.rb, config/initializers/session_store.rb, db/migrate/20240808191832_add_sessions_table.rb, db/schema.rb
Closes #544
This changes sessions to be stored in the database instead of in the cookies itself. That should fix the issue with cookies getting too large.
=> Change sessions to be stored in the database

app/controllers/adjectives_controller.rb, app/controllers/function_words_controller.rb, app/controllers/nouns_controller.rb, app/controllers/seo_controller.rb, app/controllers/verbs_controller.rb, app/services/slug_constraint.rb, app/views/adjectives/show.json.jbuilder, app/views/function_words/show.json.jbuilder, app/views/nouns/show.json.jbuilder, app/views/seo/word_index.json.jbuilder, app/views/verbs/show.json.jbuilder
Closes #549.
Adds:
- JSON response for single words: `/haus.json`
- JSON response for word index: `/seite/wort-index/a.json` (you need to iterate the letters)
=> JSON endpoints for single words and word index

app/components/visual_overview_links_component.html.haml, app/components/visual_overview_links_component.rb, app/views/hierarchies/index.html.haml, app/views/homes/show.html.haml, app/views/keywords/index.html.haml, app/views/topics/index.html.haml
=> Add links to visual overviews

config/deploy.rb
This adds the LLM model configuration in case the `.env` file is newly created on a deployment.
=> Add LLM model configuration

app/controllers/reviews_controller.rb, app/jobs/enrich_word_job.rb, spec/features/reviews/new_word_spec.rb
If a new word is added to the database, this automatically starts the LLM enrichment of that word.
=> LLM | Enrich new words

app/models/compound_entity.rb
=> Fix sending compound entities to LLM

app/helpers/kaminari_helper.rb, app/models/keyword.rb, app/views/keywords/index.html.haml, app/views/keywords/show.html.haml, config/locales/models.de.yml
Closes #616.
- Changes pagination label
- Changes word count to take into account all keywords
=> Keywords | Pagination label and count

app/models/keyword.rb
Closes #616.
Fixes the keyword index if you have not yet selected a keyword.
=> Fix keyword index without any given keyword IDs

app/controllers/word_images_controller.rb, app/models/ability.rb, app/views/pages/navigation.html.haml, app/views/word_images/index.html.haml, config/locales/navigation.de.yml, config/locales/views.de.yml, config/routes.rb, spec/requests/word_images_controller_spec.rb
Closes #619
Adds a list of words with images:
=> Add list of words with images

app/services/llm/enrich.rb, app/services/llm/schema/keywords.rb, app/services/llm/schema/shared.rb
This adds an additional LLM prompt to find keywords.
=> LLM | Keywords prompt

app/services/llm/enrich.rb
=> Fix display of prompt for words

app/components/theme_component.html.haml, app/services/llm/enrich.rb
This adds the keywords LLM prompt at the bottom of the page.
=> LLM | Add keywords prompt to website

app/components/reviews/llm_value_component.html.haml, app/javascript/controllers/toggle_buttons_controller.js, app/models/concerns/reviewable.rb, config/locales/components.de.yml, spec/features/reviews/word_attribute_edit_spec.rb
Changes the select list to toggle buttons in the review:
=> Reviews | Change arrays from select to toggle buttons

app/controllers/llm_prompts_controller.rb, app/models/ability.rb, app/models/llm_prompt.rb, app/services/llm/enrich.rb, app/views/llm_prompts/edit.html.haml, app/views/llm_prompts/index.html.haml, app/views/pages/navigation.html.haml, config/locales/models.de.yml, config/locales/navigation.de.yml, config/locales/views.de.yml, config/routes.rb, db/migrate/20250325200424_create_llm_prompts.rb, db/schema.rb, spec/services/import/word_spec.rb, spec/services/llm/enrich_spec.rb
Closes #673.
This moves the LLM prompts to the database and allows them to be edited in the UI.
=> LLM Prompts | Edit

app/controllers/reviewables/garbage_collections_controller.rb, app/jobs/reviews/delete_open_job.rb, app/models/concerns/reviewable.rb, app/views/pages/navigation.html.haml, app/views/reviewables/garbage_collections/new.html.haml, app/views/reviewables/garbage_collections/show.html.haml, config/locales/navigation.de.yml, config/locales/views.de.yml, config/routes.rb
Closes #675.
Adds a page with a button to delete all open reviews.
=> Reviews | Delete open

app/controllers/llm_enrichments_controller.rb, app/form_objects/forms/llm_enrichment_list.rb, app/jobs/enrich_word_list_job.rb, app/models/ability.rb, app/views/llm_enrichments/new.html.haml, app/views/llm_enrichments/show.html.haml, app/views/pages/navigation.html.haml, config/locales/models.de.yml, config/locales/navigation.de.yml, config/locales/views.de.yml, config/routes.rb
Closes #674.
This adds manual enrichment of existing words:
You can choose a word list and it will schedule an enrichment job for every word on the list.
=> LLM | Manual enrichment

app/views/searches/show.turbo_stream.haml
=> Fix update of "add to word list" when searching

app/controllers/llm_prompts_controller.rb
=> Fix storing LLM prompts

app/models/llm_prompt.rb, app/services/llm/enrich.rb, spec/services/llm/enrich_spec.rb
Empty LLM prompts will no longer be sent to the LLM.
=> Change empty prompts not to be sent to LLM

app/controllers/llm_services/activations_controller.rb, app/controllers/llm_services_controller.rb, app/models/ability.rb, app/models/llm_service.rb, app/services/llm/invoke.rb, app/views/llm_services/_form.html.haml, app/views/llm_services/edit.html.haml, app/views/llm_services/index.html.haml, app/views/llm_services/new.html.haml, app/views/pages/navigation.html.haml, config/locales/models.de.yml, config/locales/navigation.de.yml, config/locales/notices.de.yml, config/locales/views.de.yml, config/routes.rb, db/migrate/20250430193924_create_llm_services.rb, db/schema.rb, spec/factories/llm_services.rb, spec/features/reviews/unlisted_keywords_spec.rb, spec/rails_helper.rb, spec/services/import/word_spec.rb, spec/services/llm/enrich_spec.rb
Related to #697.
Adds CRUD for LLM services and allows to activate one. The active one will be used when the LLM is invoked.
=> LLM Services

Gemfile, Gemfile.lock, app/models/llm_service.rb
Related to #697.
Should fix invoking OpenAI.
=> Fix LLM invocation for OpenAI
